CREATE DATABASE SalesDB;
USE SalesDB;
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(50),
    Category VARCHAR(50),
    UnitPrice INT
);
INSERT INTO Products (ProductID, ProductName, Category, UnitPrice) VALUES
(1, 'Laptop', 'Electronics', 1000),
(2, 'Printer', 'Electronics', 400),
(3, 'Monitor', 'Electronics', 300),
(4, 'Keyboard', 'Accessories', 100);

CREATE TABLE Sales (
    SaleID INT PRIMARY KEY,
    Salesperson VARCHAR(50),
    Region VARCHAR(50),
    Product VARCHAR(50),
    Quantity INT,
    Revenue INT,
    SaleDate DATE
);

INSERT INTO Sales (SaleID, Salesperson, Region, Product, Quantity, Revenue, SaleDate) VALUES
(1, 'John', 'North', 'Laptop', 3, 3000, '2023-01-10'),
(2, 'Emma', 'South', 'Printer', 2, 800, '2023-01-15'),
(3, 'Ava', 'North', 'Laptop', 1, 1000, '2023-01-20'),
(4, 'Noah', 'East', 'Monitor', 4, 1200, '2023-02-01'),
(5, 'John', 'North', 'Keyboard', 5, 500, '2023-02-05'),
(6, 'Emma', 'South', 'Monitor', 1, 300, '2023-02-10'),
(7, 'Ava', 'West', 'Laptop', 2, 2000, '2023-02-15'),
(8, 'Noah', 'East', 'Printer', 3, 1200, '2023-02-20'),
(9, 'John', 'North', 'Monitor', 2, 600, '2023-03-01'),
(10, 'Emma', 'South', 'Laptop', 1, 1000, '2023-03-05');

#1. Find the sales where the product category is 'Electronics'.
SELECT * FROM Sales
WHERE Product IN (
  SELECT ProductName FROM Products
  WHERE Category = 'Electronics'
);

#2. List all sales where the unit price of the product is greater than 500.
SELECT * FROM Sales
WHERE Product IN (
  SELECT ProductName FROM Products
  WHERE UnitPrice > 500
);


#3. Get the total revenue generated by each product category.
SELECT Category, SUM(Revenue) AS TotalRevenue
FROM Sales s
JOIN Products p ON s.Product = p.ProductName
GROUP BY Category;


#4. Find the sales made for products that belong to the 'Accessories' category.
SELECT * FROM Sales
WHERE Product IN (
  SELECT ProductName FROM Products
  WHERE Category = 'Accessories'
);


#5. List sales where the product name matches the most sold product.
SELECT * FROM Sales
WHERE Product = (
  SELECT Product
  FROM Sales
  GROUP BY Product
  ORDER BY SUM(Quantity) DESC
  LIMIT 1
);


#6. Get the salespersons who sold products from more than one category.
SELECT Salesperson
FROM Sales s
JOIN Products p ON s.Product = p.ProductName
GROUP BY Salesperson
HAVING COUNT(DISTINCT Category) > 1;


#7. Show all products that were never sold.
SELECT * FROM Products
WHERE ProductName NOT IN (
  SELECT DISTINCT Product FROM Sales
);


#8. Find the average revenue per product category.
SELECT Category, AVG(Revenue) AS AvgRevenue
FROM Sales s
JOIN Products p ON s.Product = p.ProductName
GROUP BY Category;


#9. List the sales with revenue higher than the average revenue for that product category.
SELECT * FROM Sales s
WHERE Revenue > (
  SELECT AVG(Revenue)
  FROM Sales s2
  JOIN Products p2 ON s2.Product = p2.ProductName
  WHERE p2.Category = (
    SELECT Category FROM Products p WHERE p.ProductName = s.Product
  )
);

#10. Find products whose unit price is greater than the average revenue of all sales.
SELECT * FROM Products
WHERE UnitPrice > (
  SELECT AVG(Revenue) FROM Sales
);

